adding support in command line for xm|xl
sensu-plugins/sensu-plugins-xen pull request #3
Opened 2016-05-23 18:41 UTC by mag009

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose

#### Known Compatablity Issues

2016-05-24 08:35 UTC, eheydrick commented on bin/metrics-xen.rb
> +  option :info,
can you rename this option to `info_command` so it's more clear what it is.

2016-05-24 08:35 UTC, eheydrick commented
Left a comment, otherwise looks good. Thanks!

2016-05-27 23:02 UTC, mag009 commented
there you go, thanks!

2016-06-02 12:06 UTC, sstarcher commented on bin/metrics-xen.rb
> +         default: 'xl'
the previous default was xm

2017-05-03 03:12 UTC, majormoses requested changes

2017-05-03 03:12 UTC, majormoses commented on CHANGELOG.md
> +## [0.0.4] - 2016-05-23
remove version we will bump on release.

2017-05-03 03:12 UTC, majormoses commented on bin/metrics-xen.rb
> +         default: 'xl'
please change to keep this backwards compatible.

2017-05-03 20:17 UTC, mag009 commented on CHANGELOG.md
> +## [0.0.4] - 2016-05-23
sure no problem

2017-05-03 20:22 UTC, mag009 reviewed
made the changes requested cheers

2017-05-03 20:22 UTC, mag009 commented on bin/metrics-xen.rb
> +         default: 'xl'
you mean change the default to xm?

2017-05-03 21:18 UTC, majormoses commented
@mag009 
I checked and the issue is only with ruby < 2 which we dont support, I am ok with merging this and I will need to remove testing for 2.x before we can release (it wont let me)

2017-05-03 21:19 UTC, majormoses approved these changes
CI issues are ruby 1.9 and I will fix prior to release.

2017-05-03 21:19 UTC, merged